language: go
go:
    - master
git:
    depth: false
before_install:
    - echo -e "machine github.com\n login $GITHUB_TOKEN" > ~/.netrc
    - git lfs pull
script: go test -v -cover ./server/lib/emails
